// apps/web/src/components/transaction/DepositForm.tsx
import { useState } from 'react'
import { v4 as uuidv4 } from 'uuid'
import { usePrimaryAccount } from '@/hooks/useAccounts'
import { useDeposit } from '@/hooks/useTransactions'
import Button from '@/components/common/Button'
import Input from '@/components/common/Input'

export default function DepositForm() {
  const { primaryAccount } = usePrimaryAccount()
  const depositMutation = useDeposit()

  const [amount, setAmount] = useState('')
  const [description, setDescription] = useState('')
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [successMessage, setSuccessMessage] = useState<string | null>(null)

  const currentBalance = primaryAccount?.balance ?? '0.00'
  const accountId = primaryAccount?.id ?? ''

  const numAmount = parseFloat(amount)
  const isValidAmount = !isNaN(numAmount) && numAmount > 0
  const canSubmit = isValidAmount && !depositMutation.isPending

  function formatCurrency(value: string): string {
    const num = parseFloat(value)
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: primaryAccount?.currency || 'BRL',
    }).format(num)
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()

    if (!canSubmit) {
      setErrorMessage('Please enter a valid amount')
      return
    }

    setErrorMessage(null)
    setSuccessMessage(null)

    try {
      const result = await depositMutation.mutateAsync({
        accountId,
        request: {
          idempotency_key: uuidv4(),
          amount,
          description,
        },
      })

      if (result.success) {
        setSuccessMessage(`Deposit of ${formatCurrency(amount)} completed successfully!`)
        setAmount('')
        setDescription('')
      } else {
        setErrorMessage(result.error_message || 'Deposit failed')
      }
    } catch (e: unknown) {
      const err = e as { response?: { data?: { error_message?: string; error?: string } } }
      setErrorMessage(err.response?.data?.error_message || err.response?.data?.error || 'Deposit failed')
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
        <p className="text-sm text-gray-600 dark:text-gray-400">Your Balance</p>
        <p className="text-2xl font-bold text-primary-600">{formatCurrency(currentBalance)}</p>
      </div>

      <Input
        value={amount}
        onChange={setAmount}
        label="Amount"
        type="number"
        step="0.01"
        min="0.01"
        placeholder="0.00"
        required
        error={amount && !isValidAmount ? 'Please enter a valid amount greater than 0' : undefined}
      />

      <Input
        value={description}
        onChange={setDescription}
        label="Description (optional)"
        placeholder="What's this deposit for?"
      />

      {errorMessage && (
        <div className="bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 px-4 py-3 rounded-lg text-sm">
          {errorMessage}
        </div>
      )}

      {successMessage && (
        <div className="bg-green-50 dark:bg-green-900/30 border border-green-200 dark:border-green-800 text-green-700 dark:text-green-400 px-4 py-3 rounded-lg text-sm">
          {successMessage}
        </div>
      )}

      <Button type="submit" disabled={!canSubmit} loading={depositMutation.isPending} className="w-full">
        Deposit
      </Button>
    </form>
  )
}

// apps/web/src/components/transaction/DepositForm.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { v4 as uuidv4 } from 'uuid'
import { useTransactionStore } from '@/stores/transaction'
import { useAccountStore } from '@/stores/account'
import Button from '@/components/common/Button.vue'
import Input from '@/components/common/Input.vue'

const transactionStore = useTransactionStore()
const accountStore = useAccountStore()

const amount = ref('')
const description = ref('')
const isSubmitting = ref(false)
const errorMessage = ref<string | null>(null)
const successMessage = ref<string | null>(null)

const currentBalance = computed(() => accountStore.primaryAccount?.balance ?? '0.00')
const accountId = computed(() => accountStore.primaryAccount?.id ?? '')

const isValidAmount = computed(() => {
  const numAmount = parseFloat(amount.value)
  return !isNaN(numAmount) && numAmount > 0
})

const canSubmit = computed(() => {
  return isValidAmount.value && !isSubmitting.value
})

async function handleSubmit() {
  if (!canSubmit.value) {
    errorMessage.value = 'Please enter a valid amount'
    return
  }

  isSubmitting.value = true
  errorMessage.value = null
  successMessage.value = null

  const idempotencyKey = uuidv4()

  const result = await transactionStore.deposit(accountId.value, {
    idempotency_key: idempotencyKey,
    amount: amount.value,
    description: description.value,
  })

  if (result.success) {
    successMessage.value = `Deposit of ${formatCurrency(amount.value)} completed successfully!`
    amount.value = ''
    description.value = ''
    await accountStore.fetchAccounts()
  } else {
    errorMessage.value = result.error_message || 'Deposit failed'
  }

  isSubmitting.value = false
}

function formatCurrency(value: string): string {
  const num = parseFloat(value)
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: accountStore.primaryAccount?.currency || 'BRL',
  }).format(num)
}
</script>

<template>
  <form @submit.prevent="handleSubmit" class="space-y-6">
    <div class="bg-gray-50 dark:bg-gray-700 rounded-lg p-4">
      <p class="text-sm text-gray-600 dark:text-gray-400">Your Balance</p>
      <p class="text-2xl font-bold text-primary-600">{{ formatCurrency(currentBalance) }}</p>
    </div>

    <Input
      v-model="amount"
      label="Amount"
      type="number"
      step="0.01"
      min="0.01"
      placeholder="0.00"
      required
      :error="amount && !isValidAmount ? 'Please enter a valid amount greater than 0' : undefined"
    />

    <Input
      v-model="description"
      label="Description (optional)"
      placeholder="What's this deposit for?"
    />

    <div v-if="errorMessage" class="bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 px-4 py-3 rounded-lg text-sm">
      {{ errorMessage }}
    </div>

    <div v-if="successMessage" class="bg-green-50 dark:bg-green-900/30 border border-green-200 dark:border-green-800 text-green-700 dark:text-green-400 px-4 py-3 rounded-lg text-sm">
      {{ successMessage }}
    </div>

    <Button type="submit" :disabled="!canSubmit" :loading="isSubmitting" class="w-full">
      Deposit
    </Button>
  </form>
</template>
